create table if not exists crossword_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null,
  level integer not null check (level between 1 and 6),
  puzzle_key text not null,
  is_public boolean not null default false,
  completed_at timestamptz not null default now()
);

create index if not exists crossword_completions_completed_at_idx
  on crossword_completions (completed_at desc);

create index if not exists crossword_completions_user_id_idx
  on crossword_completions (user_id, completed_at desc);

alter table crossword_completions enable row level security;

drop policy if exists "users insert own crossword completions" on crossword_completions;
create policy "users insert own crossword completions"
  on crossword_completions for insert
  with check (auth.uid() = user_id);

drop policy if exists "users read own crossword completions" on crossword_completions;
create policy "users read own crossword completions"
  on crossword_completions for select
  using (auth.uid() = user_id);

drop policy if exists "public read public crossword completions" on crossword_completions;
create policy "public read public crossword completions"
  on crossword_completions for select
  using (is_public = true);

drop policy if exists "teachers read all crossword completions" on crossword_completions;
create policy "teachers read all crossword completions"
  on crossword_completions for select
  using (public.is_teacher());
