const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, '..', 'src', 'grammar.json');
const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

const examples = {
  0:  ["책이 있어요. (There is a book.)", "의자가 있어요. (There is a chair.)"],
  1:  ["밥과 국을 먹었어요. (I ate rice and soup.)", "사과와 바나나를 샀어요. (I bought apples and bananas.)"],
  2:  ["서울에서 부산까지 기차로 가요. (I go from Seoul to Busan by train.)", "아홉 시까지 기다렸어요. (I waited until 9 o'clock.)"],
  3:  ["선생님께서 교실에 들어오셨어요. (The teacher entered the classroom.)", "할머니께서 밥을 드세요. (Grandmother is eating.)"],
  4:  ["책은 읽었지만 숙제는 안 했어요. (I read the book but didn't do the homework.)", "언니는 키가 크지만 저는 작아요. (My sister is tall but I am short.)"],
  5:  ["저도 한국어를 공부해요. (I also study Korean.)", "이 음식도 맛있어요. (This food is also delicious.)"],
  6:  ["책을 읽어요. (I read a book.)", "사과를 먹어요. (I eat an apple.)"],
  7:  ["국이랑 밥을 같이 먹어요. (I eat soup and rice together.)", "친구랑 같이 영화를 봤어요. (I watched a movie with a friend.)"],
  8:  ["오른쪽으로 가세요. (Please go to the right.)", "버스로 가요. (I go by bus.)"],
  9:  ["아홉 시부터 일해요. (I work from 9 o'clock.)", "어제부터 비가 와요. (It has been raining since yesterday.)"],
  10: ["학교에 가요. (I go to school.)", "서울에 살아요. (I live in Seoul.)"],
  11: ["친구에게 편지를 썼어요. (I wrote a letter to a friend.)", "선생님에게 질문했어요. (I asked the teacher a question.)"],
  12: ["학교에서 공부해요. (I study at school.)", "미국에서 왔어요. (I came from the United States.)"],
  13: ["이것은 선생님의 책이에요. (This is the teacher's book.)", "나의 꿈은 의사가 되는 거예요. (My dream is to become a doctor.)"],
  14: ["사과하고 배를 샀어요. (I bought apples and pears.)", "나하고 같이 가요. (Go with me.)"],
  15: ["저만 한국어를 공부해요. (Only I study Korean.)", "물만 마셔요. (I only drink water.)"],
  16: ["저는 학생이에요. (I am a student.)", "이것은 책이에요. (This is a book.)"],
  17: ["친구한테 전화했어요. (I called a friend.)", "선생님한테 물어봤어요. (I asked the teacher.)"],
  18: ["오늘이 어제보다 더 추워요. (Today is colder than yesterday.)", "언니보다 제가 더 커요. (I am taller than my older sister.)"],
  19: ["내일 일찍 일어나겠어요. (I will wake up early tomorrow.)", "많이 배고프시겠어요. (You must be very hungry.)"],
  20: ["어제 밥을 먹었어요. (I ate rice yesterday.)", "어제 친구를 만났어요. (I met a friend yesterday.)"],
  21: ["선생님께서 앉으셨어요. (The teacher sat down.)", "어머니께서 오셨어요. (Mother came.)"],
  22: ["음악을 듣고 책을 읽어요. (I listen to music and read books.)"],
  23: ["배가 고프니까 밥을 먹어요. (Since I'm hungry, I eat.)", "시간이 없으니까 빨리 갑시다. (Since we have no time, let's go quickly.)"],
  24: ["책을 사러 서점에 가요. (I go to the bookstore to buy books.)", "밥을 먹으러 식당에 갔어요. (I went to the restaurant to eat.)"],
  25: ["배가 고파서 밥을 먹어요. (I'm hungry so I eat.)", "비가 와서 우산을 가져왔어요. (It rained so I brought an umbrella.)"],
  26: ["비가 오지만 나가요. (It rains but I go out.)", "가격이 비싸지만 맛있어요. (It's expensive but delicious.)"],
  27: ["건강해지려고 운동을 해요. (I exercise in order to get healthy.)", "한국어를 배우려고 학원에 다녀요. (I attend a language school to learn Korean.)"],
  28: ["지금 어디에 가십니까? (Where are you going now?)", "밥을 먹습니까? (Are you eating?)"],
  29: ["저는 학생입니다. (I am a student.)", "밥을 먹습니다. (I eat rice.)"],
  30: ["같이 먹읍시다. (Let's eat together.)", "빨리 갑시다. (Let's go quickly.)"],
  31: ["여기 앉으세요. (Please sit here.)", "이쪽으로 오세요. (Please come this way.)"],
  32: ["자리에 앉으십시오. (Please take a seat.)", "이쪽으로 오십시오. (Please come this way.)"],
  33: ["저도 학생이에요. 언니도 학생이고요. (I'm a student too. And my sister is also a student.)"],
  34: ["우리 같이 밥 먹을까요? (Shall we eat together?)", "지금 갈까요? (Shall we go now?)"],
  35: ["오늘 뭐 해? (What are you doing today?)", "밥 먹어? (Are you eating?)"],
  36: ["이것은 제 가방이 아니에요. (This is not my bag.)", "저는 의사가 아니에요. (I am not a doctor.)"],
  37: ["한국에 가고 싶어요. (I want to go to Korea.)"],
  38: ["지금 공부하고 있어요. (I am studying now.)"],
  39: ["8시까지 와야 돼요. (You have to come by 8 o'clock.)", "이 약을 먹어야 돼요. (You have to take this medicine.)"],
  40: ["오늘은 학교에 가지 않아요. (I don't go to school today.)", "이 음식은 맛있지 않아요. (This food is not delicious.)"],
  41: ["한국어를 할 수 있어요. (I can speak Korean.)"],
  42: ["오늘은 밥을 먹지 못했어요. (I couldn't eat today.)", "한국어를 잘 하지 못해요. (I can't speak Korean well.)"],
  43: ["밥을 먹기 전에 손을 씻어요. (I wash my hands before eating.)", "자기 전에 이를 닦아요. (I brush my teeth before sleeping.)"],
  44: ["밥을 먹은 후에 산책해요. (I take a walk after eating.)", "학교에 간 후에 공부해요. (I study after going to school.)"],
  45: ["선생님께 선물을 드렸어요. (I gave a gift to the teacher.)", "할머니께 전화를 드렸어요. (I called my grandmother.)"],
  46: ["매일 운동을 해요. (I exercise every day.)", "주마다 한 번씩 청소해요. (I clean once every week.)"],
  47: ["천 원밖에 없어요. (I only have 1,000 won.)", "이것밖에 없어요. (There is only this.)"],
  48: ["얼음처럼 차가워요. (It's cold like ice.)", "선생님처럼 잘 가르쳐요. (I teach well like the teacher.)"],
  49: ["서울에서부터 걸어왔어요. (I walked all the way from Seoul.)", "아침부터 공부했어요. (I studied from morning.)"],
  50: ["책상에다가 꽃을 놓았어요. (I put flowers on the desk.)", "가방에다가 책을 넣었어요. (I put books in the bag.)"],
  51: ["친구에게로 편지를 보냈어요. (I sent a letter toward my friend.)", "선생님에게로 다가갔어요. (I approached toward the teacher.)"],
  52: ["친구에게서 편지를 받았어요. (I received a letter from a friend.)", "선생님에게서 배웠어요. (I learned from the teacher.)"],
  53: ["친구한테서 선물을 받았어요. (I received a gift from a friend.)", "동생한테서 전화가 왔어요. (A call came from my younger sibling.)"],
  54: ["국이나 찌개를 먹어요. (I eat soup or stew.)", "커피나 차를 마셔요. (I drink coffee or tea.)"],
  55: ["집에 가거나 카페에 가요. (I go home or I go to a cafe.)", "먹거나 마셔요. (I eat or drink.)"],
  56: ["날씨가 좋은데 밖에 안 나가요. (The weather is nice but I'm not going out.)", "배가 고픈데 음식이 없어요. (I'm hungry but there's no food.)"],
  57: ["시간이 있으면 와요. (If you have time, come.)", "돈이 많으면 여행을 가겠어요. (If I had a lot of money, I would travel.)"],
  58: ["음악을 들으면서 공부해요. (I study while listening to music.)", "웃으면서 이야기해요. (I talk while smiling.)"],
  59: ["잘 보이게 크게 써 주세요. (Please write it big so it's easy to see.)", "따뜻하게 입으세요. (Please dress warmly.)"],
  60: ["TV를 보다가 잠이 들었어요. (I fell asleep while watching TV.)", "밥을 먹다가 전화가 왔어요. (A call came while I was eating.)"],
  61: ["수영하기가 좋아요. (I like swimming.)", "한국어 공부하기가 어려워요. (Studying Korean is difficult.)"],
  62: ["지금 먹는 음식이 뭐예요? (What food are you eating now?)", "한국어를 가르치는 선생님이에요. (He is a teacher who teaches Korean.)"],
  63: ["어제 먹은 음식이 맛있었어요. (The food I ate yesterday was delicious.)", "읽은 책을 반납했어요. (I returned the book I read.)"],
  64: ["내일 먹을 음식을 준비했어요. (I prepared food to eat tomorrow.)", "갈 곳이 있어요. (I have a place to go.)"],
  65: ["닫힌 문을 열었어요. (I opened the closed door.)", "배운 내용을 복습했어요. (I reviewed what I learned.)"],
  66: ["그의 웃음이 보기 좋았어요. (His smile was nice to see.)", "성공함이 목표예요. (Succeeding is the goal.)"],
  67: ["날씨가 정말 좋은군! (The weather is really nice!)", "그 사람이 벌써 왔군! (That person already came!)"],
  68: ["내가 할게요. (I will do it.)", "제가 도와줄게요. (I will help you.)"],
  69: ["빨리 와, 기다리고 있잖아. (Come quickly, we're waiting.)", "그냥 말하지 그래요. (Just go ahead and say it.)"],
  70: ["오늘 날씨가 정말 좋은데요! (The weather is really nice today!)", "이 음식이 맛있는데요! (This food is really delicious!)"],
  71: ["꽃이 정말 예쁘네요. (The flowers are really pretty.)", "오늘 날씨가 춥네요. (The weather is cold today.)"],
  72: ["같이 갈래요? (Would you like to go together?)", "뭐 먹을래요? (What do you want to eat?)"],
  73: ["한국어를 배우게 됐어요. (I came to learn Korean.)"],
  74: ["피곤하기 때문에 쉬어요. (I rest because I'm tired.)", "바쁘기 때문에 못 가요. (I can't go because I'm busy.)"],
  75: ["내일부터 운동하기로 했어요. (I decided to exercise starting tomorrow.)", "같이 여행 가기로 했어요. (We decided to go on a trip together.)"],
  76: ["비가 올 것 같아요. (It seems like it will rain.)"],
  77: ["한국에 온 지 3년이 됐어요. (It has been 3 years since I came to Korea.)", "밥을 먹은 지 두 시간이 지났어요. (Two hours have passed since I ate.)"],
  78: ["운동하는 것이 건강에 좋아요. (Exercising is good for health.)", "한국어를 공부하는 것이 재미있어요. (Studying Korean is fun.)"],
  79: ["수업하는 동안에 조용히 하세요. (Please be quiet while class is in session.)", "밥 먹는 동안에 TV를 봐요. (I watch TV while eating.)"],
  80: ["제주도에 가 본 적이 있어요. (I have been to Jeju Island.)", "한국 음식을 먹어 본 적이 있어요. (I have tried Korean food.)"],
  81: ["지시에 따를 것! (Follow the instructions!)", "안전벨트를 착용할 것. (Wear a seatbelt.)"],
  82: ["어릴 때 공부를 열심히 했어요. (I studied hard when I was young.)", "피곤할 때 쉬어야 해요. (You should rest when you're tired.)"],
  83: ["비가 올까 봐 우산을 가져왔어요. (I brought an umbrella in case it rains.)", "늦을까 봐 일찍 출발했어요. (I left early in case I would be late.)"],
  84: ["한번 먹어 봐요. (Try eating it once.)", "한번 입어 봐요. (Try wearing it once.)"],
  85: ["문이 열려 있어요. (The door is open.)", "꽃이 피어 있어요. (The flowers are in bloom.)"],
  86: ["문을 열어 줬어요. (I opened the door for someone.)", "가방을 들어 줬어요. (I carried the bag for someone.)"],
  87: ["여기 앉아도 돼요. (You may sit here.)", "이거 먹어도 돼요. (You may eat this.)"],
  88: ["여기서 담배를 피우지 마세요. (Please don't smoke here.)", "큰 소리로 말하지 마세요. (Please don't speak loudly.)"],
  89: ["그 영화를 볼 수밖에 없었어요. (I had no choice but to watch that movie.)", "기다릴 수밖에 없어요. (I have no choice but to wait.)"],
  90: ["선생님같이 말해요. (I speak like the teacher.)", "친구같이 편하게 이야기해요. (I talk comfortably like a friend.)"],
  91: ["학생이고 선생님이고 모두 왔어요. (Both students and teachers came.)", "일이고 공부고 다 잘해요. (He does well in both work and study.)"],
  92: ["말한 대로 해요. (Do it as I said.)", "약속한 대로 왔어요. (I came as I promised.)"],
  93: ["부모님으로부터 용돈을 받았어요. (I received allowance from my parents.)", "회사로부터 연락이 왔어요. (A message came from the company.)"],
  94: ["생각만큼 어렵지 않아요. (It's not as difficult as I thought.)", "키가 저만큼 커요. (He is as tall as me.)"],
  95: ["엄마보고 왜 그랬냐고 했어요. (I asked my mom why she did that.)", "친구보고 빨리 오라고 했어요. (I told my friend to come quickly.)"],
  96: ["저뿐만 아니라 친구도 왔어요. (Not only I but my friend also came.)", "이것뿐이에요. (This is all there is.)"],
  97: ["철수야, 밥 먹어! (Cheolsu, eat!)", "민수야, 여기 와! (Minsu, come here!)"],
  98: ["저도요. (Me too.)", "맞아요. 그리고요? (That's right. And?)"],
  99: ["집이라고 해요. (They call it 'house'.)", "선생님이라고 불러요. (Please call me teacher.)"],
  100: ["그때는 학생이었었어요. (I had been a student back then.)", "예전에 거기 살았었어요. (I used to live there before.)"],
  101: ["비가 오거든 전화해요. (Call me if it rains.)", "시간이 있거든 와요. (Come if you have time.)"],
  102: ["먹는다거나 마신다거나 해요. (I eat or drink, things like that.)", "공부한다거나 운동한다거나 해요. (I study or exercise, things like that.)"],
  103: ["바쁘다고 못 간대요. (They say they can't go because they're busy.)", "맛있다고 많이 먹었어요. (I ate a lot saying it was delicious.)"],
  104: ["날씨가 좋으나 춥네요. (The weather is nice but cold.)", "열심히 하나 결과가 없어요. (I work hard but there are no results.)"],
  105: ["공부하느라고 잠을 못 잤어요. (I couldn't sleep because I was studying.)", "숙제를 하느라고 늦었어요. (I was late because I was doing homework.)"],
  106: ["알아듣도록 천천히 말해요. (I speak slowly so that they can understand.)", "빨리 오도록 전화했어요. (I called so that they would come quickly.)"],
  107: ["마트에서 사다가 냉장고에 넣었어요. (I bought it from the market and put it in the fridge.)", "도서관에서 빌려다가 읽었어요. (I borrowed it from the library and read it.)"],
  108: ["비가 와도 가요. (Even if it rains, I go.)", "돈이 없어도 행복해요. (Even without money, I am happy.)"],
  109: ["열심히 공부해야 해요. (You have to study hard.)", "밥을 먹어야 힘이 나요. (You have to eat to have energy.)"],
  110: ["일찍 자야지. (I should sleep early.)", "빨리 가야지. (I should go quickly.)"],
  111: ["약을 먹었더니 나았어요. (I took medicine and got better.)", "음식을 먹었더니 배가 불러요. (I ate food and now I'm full.)"],
  112: ["집에 도착하자마자 전화했어요. (I called as soon as I arrived home.)", "밥을 먹자마자 나갔어요. (I went out as soon as I finished eating.)"],
  113: ["가다가 친구를 만났어요. (I met a friend while going somewhere.)", "공부하다가 쉬었어요. (I rested while studying.)"],
  114: ["날씨가 좋으니 산책하러 가요. (The weather is nice so let's go for a walk.)", "피곤하니 쉬세요. (You're tired so please rest.)"],
  115: ["한국어를 잘 하려면 매일 연습해야 해요. (If you want to speak Korean well, you have to practice every day.)", "건강해지려면 운동을 해야 해요. (If you want to be healthy, you have to exercise.)"],
  116: ["예전에 살던 집이 그리워요. (I miss the house I used to live in.)", "자주 가던 카페가 문을 닫았어요. (The cafe I used to frequent has closed.)"],
  117: ["제가 바쁘거든요. 나중에 할게요. (I'm busy, you see. I'll do it later.)", "그 사람이 착하거든요. 그래서 좋아해요. (He's kind, you know. That's why I like him.)"],
  118: ["드디어 봄이 오는구나! (Spring is finally coming!)", "그 친구가 열심히 공부하는구나! (That friend really studies hard!)"],
  119: ["매일 운동을 한다. (I exercise every day.)", "학생들이 열심히 공부한다. (Students study hard.)"],
  120: ["그 책이 재미있던데요! (That book was really interesting!)", "생각보다 맛있던데요! (It was more delicious than I thought!)"],
  121: ["우리 약속이 있잖아요. (We have an appointment, you know.)", "그 사람 착하잖아요. (That person is kind, isn't he?)"],
  122: ["우리 같이 먹자. (Let's eat together.)", "빨리 가자. (Let's go quickly.)"],
  123: ["벌써 다 먹었니? (Did you already eat everything?)", "숙제 다 했니? (Did you finish your homework?)"],
  124: ["아이를 웃게 했어요. (I made the child smile.)", "학생들이 열심히 공부하게 해요. (I make the students study hard.)"],
  125: ["밥을 먹고 나서 설거지를 해요. (I do the dishes after eating.)", "숙제를 끝내고 나서 놀아요. (I play after finishing homework.)"],
  126: ["비밀을 말하고 말았어요. (I ended up telling the secret.)", "늦게 일어나고 말았어요. (I ended up waking up late.)"],
  127: ["동생이 아이스크림을 먹고 싶어 해요. (My younger sibling wants to eat ice cream.)", "친구가 한국에 가고 싶어 해요. (My friend wants to go to Korea.)"],
  128: ["열심히 공부한 결과 시험에 합격했어요. (As a result of studying hard, I passed the exam.)", "꾸준히 노력한 결과 성공했어요. (As a result of steady effort, I succeeded.)"],
  129: ["밥을 먹은 다음에 산책해요. (I take a walk after eating.)", "숙제를 한 다음에 놀아요. (I play after doing homework.)"],
  130: ["밥을 먹는 대신에 과일을 먹었어요. (Instead of eating rice, I ate fruit.)", "공부하는 대신에 운동을 했어요. (Instead of studying, I exercised.)"],
  131: ["열심히 하는 만큼 결과가 좋아요. (The results are good as much as you work hard.)", "노력하는 만큼 실력이 늘어요. (Your skills improve as much as you practice.)"],
  132: ["오빠는 외향적인 반면 저는 내성적이에요. (My brother is extroverted whereas I am introverted.)", "영어는 쉬운 반면 한국어는 어려워요. (English is easy whereas Korean is difficult.)"],
  133: ["오늘 피곤한가 봐요. (You seem tired today.)", "밖에 비가 오나 봐요. (It seems like it's raining outside.)"],
  134: ["지금쯤 도착했을 텐데 왜 연락이 없죠? (They should have arrived by now, but why no contact?)", "배가 고플 텐데 뭐 먹을래요? (You must be hungry; would you like something to eat?)"],
  135: ["건강을 위해 운동해요. (I exercise for my health.)", "시험에 합격하기 위해 공부해요. (I study in order to pass the exam.)"],
  136: ["너만 아니면 다 괜찮아. (Everything is fine as long as it's not you.)", "비만 아니면 가겠어요. (I would go if it weren't for the rain.)"],
  137: ["여기서 사진 찍으면 안 돼요. (You must not take pictures here.)", "수업 중에 전화하면 안 돼요. (You must not make calls during class.)"],
  138: ["내일 비가 오지 않으면 좋겠어요. (I hope it doesn't rain tomorrow.)", "빨리 나으면 좋겠어요. (I hope you recover quickly.)"],
  139: ["한국어 실력이 점점 늘어 가요. (My Korean skills are gradually improving.)", "날이 밝아 가요. (The day is gradually getting brighter.)"],
  140: ["늦어서 택시를 타 가지고 왔어요. (I was late so I took a taxi and came.)", "물을 사 가지고 왔어요. (I bought water and brought it.)"],
  141: ["음식을 만들어 놓았어요. (I made food in advance.)", "메모를 적어 놓았어요. (I wrote down a memo in advance.)"],
  142: ["나중을 위해 돈을 아껴 두었어요. (I saved money for later.)", "음식을 냉장고에 넣어 두었어요. (I kept the food in the refrigerator.)"],
  143: ["짐을 들어 드릴게요. (I will carry your luggage for you.)", "할머니께 문을 열어 드렸어요. (I opened the door for my grandmother.)"],
  144: ["운동을 더 열심히 해야겠어요. (I really must exercise harder.)", "일찍 자야겠어요. (I really must sleep early.)"],
  145: ["날씨가 따뜻해졌어요. (The weather has gotten warmer.)", "방이 밝아졌어요. (The room has gotten brighter.)"],
  146: ["환경에 대하여 이야기했어요. (We talked about the environment.)", "그 사건에 대하여 설명해 주세요. (Please explain about that incident.)"],
  147: ["내가 할 테니 기다려요. (I'll do it, so wait.)", "비가 올 테니 우산을 가져가요. (It will rain, so take an umbrella.)"],
  148: ["10년 전부터 이 일을 해 왔어요. (I have been doing this work for 10 years.)", "꾸준히 노력해 왔어요. (I have been making steady efforts.)"],
  149: ["가기는 가는데 별로 안 좋아요. (I do go, but I don't really like it.)", "먹기는 먹었는데 배가 안 불러요. (I did eat, but I'm not full.)"],
  150: ["아직 안 온 걸 보니 바쁜 모양이에요. (Since he hasn't come yet, he seems busy.)", "큰 소리가 나는 모양이에요. (It seems like there's a loud sound.)"],
  151: ["저는 매운 걸 잘 먹는 편이에요. (I tend to eat spicy food well.)", "저는 조용한 편이에요. (I tend to be quiet.)"],
  152: ["저 사람이 사장인가 봐요. (That person seems to be the manager.)", "그 학생이 공부를 잘하는가 봐요. (That student seems to be good at studying.)"],
  153: ["지금 밥을 먹는 중이에요. (I am in the middle of eating.)", "회의를 하는 중이에요. (We are in the middle of a meeting.)"],
  154: ["나가려다가 비가 와서 못 나갔어요. (I was about to go out but couldn't because it rained.)", "전화하려다가 바빠서 못 했어요. (I was about to call but was too busy.)"],
  155: ["피곤해 보여요. (You look tired.)", "행복해 보여요. (You look happy.)"],
  156: ["그가 결혼한다고 했어요. (He said he was getting married.)", "선생님이 숙제를 하라고 했어요. (The teacher said to do the homework.)"],
  157: ["밥은커녕 물도 못 마셨어요. (I couldn't even drink water, let alone eat rice.)", "친구는커녕 가족도 없어요. (There's no family, let alone friends.)"],
  158: ["이것이나마 드세요. (Please at least have this.)", "돈이 없지만 이것이나마 드릴게요. (I have no money, but let me at least give you this.)"],
  159: ["책이며 공책이며 다 샀어요. (I bought books, notebooks, and everything.)", "사과며 배며 과일을 많이 먹어요. (I eat lots of fruit including apples and pears.)"],
  160: ["뭐가 좋든 다 괜찮아요. (Whatever is good, it's all fine.)", "가든 오든 상관없어요. (Whether you go or come, it doesn't matter.)"],
  161: ["사랑이란 상대를 배려하는 것이에요. (Love is caring for the other person.)", "행복이란 무엇일까요? (What is happiness?)"],
  162: ["이것이면 충분해요. (If it's this, it's enough.)", "다음이면 당신 차례예요. (If it's next, it's your turn.)"],
  163: ["이 일이야말로 제가 하고 싶은 일이에요. (This work is truly what I want to do.)", "지금이야말로 시작할 때예요. (Now is truly the time to start.)"],
  164: ["학생치고 공부 안 하는 사람이 있나요? (Is there a student who doesn't study?)", "이 나이치고 젊어 보여요. (For this age, they look young.)"],
  165: ["친구마저 떠나 버렸어요. (Even my friend left.)", "마지막 희망마저 사라졌어요. (Even the last hope has disappeared.)"],
  166: ["잠이라도 자야겠어요. (I should at least sleep.)", "물이라도 마셔요. (At least drink some water.)"],
  167: ["학생으로서 열심히 공부해야 해요. (As a student, I must study hard.)", "선생님으로서 책임이 있어요. (As a teacher, I have responsibility.)"],
  168: ["연필로써 글씨를 썼어요. (I wrote with a pencil.)", "대화로써 문제를 해결했어요. (I solved the problem through dialogue.)"],
  169: ["친구마저 나를 모른 척했어요. (Even my friend ignored me.)", "돈마저 없어졌어요. (Even the money is gone.)"],
  170: ["그 사람은 착하거니와 능력도 있어요. (He is kind and also capable.)", "경치가 아름답거니와 공기도 맑아요. (The scenery is beautiful, and the air is also clean.)"],
  171: ["거짓말을 하고도 뻔뻔하게 있어요. (He told a lie and still acts shamelessly.)", "밥을 먹고도 배가 고파요. (Even after eating, I'm still hungry.)"],
  172: ["환경을 보호하고자 노력해요. (I make efforts to protect the environment.)", "더 나은 삶을 살고자 일을 해요. (I work in order to live a better life.)"],
  173: ["날씨가 좋기에 산책을 나갔어요. (The weather was nice so I went for a walk.)", "늦었기에 서둘렀어요. (I hurried because I was late.)"],
  174: ["어디 사는지 몰라요. (I don't know where they live.)", "뭘 먹는지 궁금해요. (I'm curious about what they're eating.)"],
  175: ["아시다시피 그 문제는 복잡해요. (As you know, that problem is complicated.)", "말씀하셨다시피 노력이 필요해요. (As you said, effort is needed.)"],
  176: ["비가 오더라도 갈 거예요. (Even if it rains, I will go.)", "힘들더라도 포기하지 마세요. (Even if it's difficult, don't give up.)"],
  177: ["커피든지 차든지 마셔요. (Drink coffee or tea, whichever you like.)", "가든지 오든지 연락해요. (Whether you go or come, contact me.)"],
  178: ["열심히 노력하므로 성공할 거예요. (Since I work hard, I will succeed.)", "비가 오므로 외출을 안 했어요. (Since it rained, I didn't go out.)"],
  179: ["울래야 눈물도 안 나요. (I can't even cry no matter how much I try.)", "자려야 잠이 안 와요. (I can't sleep no matter how much I try.)"],
  180: ["다 끝내고서 쉬었어요. (I rested only after finishing everything.)", "밥을 먹고서 나갔어요. (I went out only after eating.)"],
  181: ["내일 날씨가 좋다면 소풍 갈 거예요. (If the weather is nice tomorrow, I'll go on a picnic.)", "시간이 있다면 같이 가요. (If you have time, let's go together.)"],
  182: ["어제는 맑더니 오늘은 비가 와요. (Yesterday it was clear but today it's raining.)", "밥을 잘 먹더니 갑자기 나갔어요. (That person was eating well but suddenly left.)"],
  183: ["비가 오던데 우산 가져왔어요? (It was raining; did you bring an umbrella?)", "음식이 맛있던데 또 오고 싶어요. (The food was delicious; I want to come again.)"],
  184: ["새처럼 날고 싶어요. (I want to fly like a bird.)", "알듯이 모르는 것도 있어요. (There are things I half-know as well.)"],
  185: ["공부할수록 모르는 게 많아요. (The more I study, the more I don't know.)", "먹을수록 맛있어요. (The more I eat, the more delicious it is.)"],
  186: ["노래하며 춤을 춰요. (I sing and dance.)", "웃으며 인사했어요. (I greeted while smiling.)"],
  187: ["뭐라는 거니? 밥이라니? (What are you saying? Rice, you say?)", "그게 사실이라니 믿을 수가 없어요. (That it's true, I can't believe it.)"],
  188: ["그 영화가 재미있더군요! (That movie was really interesting, it turns out!)", "날씨가 좋더군. (The weather was good, I see.)"],
  189: ["어제 거기 갔더라. (I went there yesterday, I recall.)", "그 음식이 생각보다 맛있더라. (That food was more delicious than I thought.)"],
  190: ["빨리 먹어라. (Eat quickly!)", "이리 와라. (Come here!)"],
  191: ["그건 내가 모르게? (As if I wouldn't know that?)", "나 없이 갔을 게 뭐야? (Why would they have gone without me?)"],
  192: ["너 결혼한다면서? (I heard you're getting married?)", "오늘 학교 안 간다면서요? (I heard you're not going to school today?)"],
  193: ["벌써 다 먹었나? (Did you already eat everything?)", "집에 갔나? (Did they go home?)"],
  194: ["그 사람이 올걸요. (I think that person will probably come.)", "이게 더 좋을걸. (I think this might be better.)"],
  195: ["이제 더 열심히 해야지. (Now I really should work harder.)", "내일은 일찍 일어나야지. (I really must wake up early tomorrow.)"],
  196: ["무슨 일 있어요? 그리고요? (Is something going on? And what else?)", "저도 갔어요. 친구도 갔고요. (I went too. And my friend went too.)"],
  197: ["그게 사실이라니 믿을 수가 없어요! (I can't believe that's true!)", "그 사람이 그런 말을 하다니 놀랍네요! (I can't believe that person said that!)"],
  198: ["말을 들을 따름이에요. (All I do is follow orders.)", "기다릴 따름이에요. (All I can do is wait.)"],
  199: ["아이가 자꾸 밖에 나가고 들어요. (The child keeps insisting on going outside.)", "그 사람이 도와주겠다고 고집스럽게 들어요. (That person insists on saying they'll help.)"],
  200: ["직접 해 보고 보니 쉽지 않네요. (After doing it myself, I found it's not easy.)", "먹고 보니 맛있었어요. (After eating it, it turned out to be delicious.)"],
  201: ["바쁘고 해서 못 갔어요. (I couldn't go, partly because I was busy.)", "비도 오고 해서 집에 있었어요. (I stayed home partly because it was also raining.)"],
  202: ["마트에 가는 김에 우유도 사왔어요. (While going to the market, I also bought milk.)", "청소하는 김에 빨래도 했어요. (While cleaning, I also did the laundry.)"],
  203: ["오는 대로 바로 연락해요. (Contact me as soon as you arrive.)", "시키는 대로 하면 돼요. (Just do as you're told.)"],
  204: ["제가 자리를 비운 사이에 전화가 왔어요. (A call came while I was away.)", "밥 먹는 사이에 비가 왔어요. (It rained while I was eating.)"],
  205: ["그 사람이 화난 듯 말했어요. (That person spoke as if angry.)", "모르는 듯 행동했어요. (They acted as if they didn't know.)"],
  206: ["수영하는 줄 알았어요. (I thought they were swimming.)", "거기 가는 줄 몰랐어요. (I didn't know they were going there.)"],
  207: ["늦잠을 잔 탓에 지각했어요. (I was late because I overslept.)", "비가 오는 탓에 소풍을 못 갔어요. (We couldn't go on the picnic because of the rain.)"],
  208: ["사과를 살까 배를 살까 고민해요. (I'm debating whether to buy apples or pears.)", "갈까 말까 고민해요. (I'm debating whether to go or not.)"],
  209: ["그 사람이 올 것인가 싶어요. (I wonder if that person will come.)", "이게 맞는 건가 싶어요. (I wonder if this is correct.)"],
  210: ["갑자기 비가 오는 바람에 옷이 다 젖었어요. (My clothes got all wet because it suddenly rained.)", "버스가 갑자기 서는 바람에 넘어졌어요. (I fell because the bus suddenly stopped.)"],
  211: ["네가 건강한 한 걱정 없어요. (As long as you are healthy, there's nothing to worry about.)", "열심히 하는 한 실패하지 않아요. (As long as you work hard, you won't fail.)"],
  212: ["폭설로 인하여 항공편이 취소됐어요. (The flight was cancelled due to heavy snow.)", "전쟁으로 인하여 많은 사람이 고통받았어요. (Many people suffered due to war.)"],
  213: ["젊을 때만 같아도 좋겠어요. (If only I were as young as before.)", "예전만 같아도 더 잘 할 수 있었을 거예요. (If only it were like before, I could have done better.)"],
  214: ["아이가 계속 울어 대요. (The child keeps crying.)", "그 사람이 큰 소리로 떠들어 대요. (That person keeps talking loudly.)"],
  215: ["날씨가 추워서인지 사람이 별로 없어요. (Perhaps because it's cold, there aren't many people.)", "피곤해서인지 집중이 안 돼요. (Perhaps because I'm tired, I can't concentrate.)"],
  216: ["상황에 따라 다르게 행동해요. (I act differently depending on the situation.)", "날씨에 따라 옷을 입어요. (I dress according to the weather.)"],
  217: ["작년에 비하여 많이 성장했어요. (Compared to last year, I have grown a lot.)", "기대에 비하여 결과가 좋지 않아요. (Compared to expectations, the results aren't good.)"],
  218: ["그 작품은 유명한 작가에 의하여 쓰였어요. (That work was written by a famous author.)", "회의는 의장에 의하여 진행됐어요. (The meeting was conducted by the chairperson.)"],
  219: ["음식을 다 먹어 버렸어요. (I finished all the food.)", "지갑을 잃어버렸어요. (I lost my wallet.)"],
  220: ["비가 올 모양이에요. (It looks like it will rain.)", "그 사람이 화난 모양이에요. (It looks like that person is angry.)"],
  221: ["넘어질 뻔했어요. (I almost fell.)", "늦을 뻔했어요. (I almost was late.)"],
  222: ["오늘 일찍 온대요. (They say they're coming early today.)", "그 사람이 간대요. (They say that person is leaving.)"],
  223: ["아이들이 뛰는 통에 잠을 못 잤어요. (I couldn't sleep because of the children running around.)", "공사 소음이 나는 통에 집중을 못 했어요. (I couldn't concentrate because of construction noise.)"],
  224: ["사과라든가 배라든가 과일을 가져오세요. (Bring some fruit, like apples or pears.)", "커피라든가 차라든가 마실 것을 준비해요. (Prepare something to drink, like coffee or tea.)"],
  225: ["강을 따라 걸었어요. (I walked along the river.)", "선생님을 따라 읽으세요. (Read along with the teacher.)"],
  226: ["이름조차 몰라요. (I don't even know the name.)", "인사조차 안 해요. (They don't even say hello.)"],
  227: ["갔지 오지는 않았어요. (They went but didn't come back.)", "먹지 않고 갔어요. (They left without eating.)"],
  228: ["착할뿐더러 능력도 있어요. (Not only is he kind, but he's also capable.)", "돈이 많을뿐더러 마음도 좋아요. (Not only does he have money, but he's also kind-hearted.)"],
  229: ["학교에 갔다가는 빨리 돌아왔어요. (After going to school, I came back quickly.)", "밥을 먹고는 바로 나갔어요. (After eating, I went out right away.)"],
  230: ["비가 오길래 우산을 가져왔어요. (I brought an umbrella because it was raining.)", "그 사람이 오길래 인사했어요. (I greeted that person because they came.)"],
  231: ["그렇게 놀다가는 시험에 떨어져요. (If you keep playing like that, you'll fail the exam.)", "이렇게 먹다가는 살이 찌겠어요. (If you keep eating like this, you'll gain weight.)"],
  232: ["어려울지라도 포기하지 않아요. (Even if it's difficult, I won't give up.)", "비가 올지라도 갈 거예요. (Even if it rains, I'll go.)"],
  233: ["집에 있느니 나가는 게 나아요. (Going out is better than staying home.)", "혼자 하느니 같이 하는 게 나아요. (Doing it together is better than doing it alone.)"],
  234: ["오늘 날씨 정말 좋네! (The weather today is really nice!)", "그 사람이 벌써 왔네! (That person is already here!)"],
  235: ["경찰이 범인을 잡았다. (The police caught the criminal.)", "대통령이 순방을 마쳤다. (The president completed an overseas tour.)"],
  236: ["그게 사실이라니! (The fact that it's true!)", "그런 말을 하다니! (To think that person said such a thing!)"],
  237: ["지금 나가려고요? (Are you trying to go out now?)", "혼자 하려고요? (Are you trying to do it alone?)"],
  238: ["빨리 가거라. (Go quickly.)", "조용히 하거라. (Be quiet.)"],
  239: ["당연하고말고요. (Of course!)", "맞고말고. (Absolutely right.)"],
  240: ["지금 뭐 하는가? (What are you doing right now?)", "거기 가는가? (Are you going there?)"],
  241: ["지금 집에 가는걸요. (I'm going home right now, you know.)", "배가 부른걸요. (I'm full, you know.)"],
  242: ["그 음식이 맛있데요. (They say that food is delicious.)", "그 사람이 착하데요. (They say that person is kind.)"],
  243: ["그 음식이 맛있더라고요. (I found that food was delicious.)", "생각보다 어렵더라고요. (It turned out harder than I thought.)"],
  244: ["빨리 오라는 거야? (Are you telling me to come quickly?)", "조용히 하라는 거야? (Are you telling me to be quiet?)"],
  245: ["예전에 다니던 학교가 없어졌어요. (The school I used to attend is gone.)", "살았던 동네가 많이 변했어요. (The neighborhood I used to live in has changed a lot.)"],
  246: ["환경 문제에 관하여 토론했어요. (We debated about environmental issues.)", "그 사건에 관하여 보고서를 썼어요. (I wrote a report about that incident.)"],
  247: ["그 사람이 일찍 오자기에 서둘렀어요. (I hurried because that person said to come early.)", "맛있다고 하자기에 먹어 봤어요. (I tried it because they said it was delicious.)"],
  248: ["사람은 실수를 하게 마련이에요. (People are bound to make mistakes.)", "좋은 일이 있으면 나쁜 일도 있게 마련이에요. (If there are good things, there are bound to be bad things too.)"],
  249: ["이제 큰일이 생기게 생겼어요. (It looks like a big problem is going to happen.)", "이대로 가다가는 실패하게 생겼어요. (The way things are going, we're bound to fail.)"],
  250: ["결과는 네가 하기 나름이야. (The result depends on how you do it.)", "성공은 노력하기 나름이에요. (Success depends on how much effort you put in.)"],
  251: ["집에 들어오기가 바쁘게 밥을 먹었어요. (As soon as I came home, I ate.)", "학교에서 돌아오기가 바쁘게 잠이 들었어요. (No sooner had I returned from school than I fell asleep.)"],
  252: ["이 길은 미끄러지기가 쉬워요. (This road tends to be slippery.)", "이 문제는 틀리기가 쉬워요. (This problem is easy to get wrong.)"],
  253: ["그 아이는 울기만 해요. (That child just cries.)", "공부하기만 했어요. (I did nothing but study.)"],
  254: ["노력하기에 따라 결과가 달라요. (The results vary depending on how you put in effort.)", "먹기에 따라 건강이 달라져요. (Your health changes depending on how you eat.)"],
  255: ["시작하기에 앞서 간단히 소개하겠습니다. (Before we begin, I will briefly introduce myself.)", "회의를 시작하기에 앞서 출석을 확인하겠습니다. (Before starting the meeting, let's check attendance.)"],
  256: ["너무 웃은 나머지 눈물이 났어요. (I laughed so much that tears came out.)", "너무 놀란 나머지 말을 못 했어요. (I was so surprised that I couldn't speak.)"],
  257: ["날씨가 춥는 데다가 바람까지 불어요. (In addition to it being cold, the wind is blowing too.)", "음식이 맛있는 데다가 가격도 싸요. (In addition to the food being delicious, the price is also low.)"],
  258: ["요리하는 동시에 전화로 이야기해요. (I talk on the phone at the same time as I cook.)", "공부하는 동시에 음악을 들어요. (I listen to music at the same time as I study.)"],
  259: ["그 사람이 슬픈 듯해요. (That person seems sad.)", "비가 올 듯해요. (It seems like it will rain.)"],
  260: ["시간이 지나면 해결되는 법이에요. (With time, things naturally get resolved.)", "노력하면 잘되는 법이에요. (If you try hard, things naturally work out.)"],
  261: ["약속한 이상 지켜야 해요. (As long as you've made a promise, you must keep it.)", "살아있는 이상 희망이 있어요. (As long as you're alive, there is hope.)"],
  262: ["신발을 신은 채로 들어오지 마세요. (Please don't come in with your shoes on.)", "눈을 감은 채로 이야기했어요. (I talked with my eyes closed.)"],
  263: ["그 사람은 모르는 척해요. (That person pretends not to know.)", "자는 척하고 있어요. (They are pretending to sleep.)"],
  264: ["어려운 상황인 가운데 최선을 다했어요. (In the midst of difficult circumstances, I did my best.)", "모든 사람이 보는 가운데 발표했어요. (I presented in front of everyone.)"],
  265: ["건강은 말할 것도 없고 행복도 중요해요. (Needless to say health, happiness is also important.)", "일은 말할 것도 없고 휴식도 필요해요. (Needless to say work, rest is also necessary.)"],
  266: ["이 영화는 볼 만해요. (This movie is worth watching.)", "그 식당은 가 볼 만해요. (That restaurant is worth visiting.)"],
  267: ["비가 올 법해요. (It seems probable that it will rain.)", "그 사람이 올 법한데요. (It seems likely that person will come.)"],
  268: ["이번에는 꼭 합격할 테다. (This time, I will certainly pass.)", "내가 직접 할 테다. (I intend to do it myself.)"],
  269: ["갈 테면 혼자 가세요. (If you're going to go, go alone.)", "할 테면 해 보세요. (If you're going to do it, go ahead.)"],
  270: ["어렵겠을 테지만 노력해 봐요. (Although it may be difficult, let's try.)", "힘들 테지만 포기하지 마세요. (Although it'll be hard, don't give up.)"],
  271: ["그 사람이 떠나려나 봐요. (It looks like that person is about to leave.)", "비가 오려나 봐요. (It seems like it might rain.)"],
  272: ["그 문제를 가지고 고민했어요. (I thought hard about that problem.)", "이걸 가지고 뭘 할 수 있어요? (What can be done with this?)"],
  273: ["비가 오면 몰라도 눈이 오지는 않아요. (It might rain, but it won't snow.)", "그 사람이면 몰라도 나는 못 해요. (If it were that person maybe, but I can't do it.)"],
  274: ["비가 오는 데도 불구하고 나갔어요. (Despite the rain, I went out.)", "어려운 데도 불구하고 포기하지 않았어요. (Despite the difficulty, I didn't give up.)"],
  275: ["공부를 열심히 하는데도 성적이 안 올라요. (Even though I study hard, my grades don't improve.)", "잠을 잤는데도 피곤해요. (Even though I slept, I'm still tired.)"],
  276: ["어렵게 문제를 풀어 냈어요. (I managed to solve the difficult problem.)", "힘들게 일을 해 냈어요. (I managed to accomplish the difficult work.)"],
  277: ["맛있다기에 먹어 봤어요. (I tried it because they said it was delicious.)", "싸다기에 많이 샀어요. (I bought a lot because they said it was cheap.)"],
  278: ["칭찬한다는 것이 그만 나쁘게 말했어요. (Meaning to praise, I inadvertently said something bad.)", "도와준다는 것이 오히려 방해가 됐어요. (Meaning to help, I instead got in the way.)"],
  279: ["늦었는데도 불구하고 기다려 줬어요. (Despite being late, they waited for me.)", "아픈데도 불구하고 출근했어요. (Despite being sick, I went to work.)"],
  280: ["반대하마는 어쩔 수 없어요. (I oppose it, but there's nothing I can do.)", "가기 싫마는 가야 해요. (I don't want to go, but I have to.)"],
  281: ["그 사람 돈 깨나 있나 봐요. (That person seems to have quite a bit of money.)", "한국어 공부 깨나 했겠네요. (You must have studied Korean quite a lot.)"],
  282: ["이것이라고 별거 없어요. (Even this is nothing special.)", "그게 집이라고 할 수 있겠어요? (Can that even be called a house?)"],
  283: ["이 일을랑 내가 할게요. (As for this matter, I'll handle it.)", "돈을랑 걱정하지 마세요. (As for money, don't worry.)"],
  284: ["고양이라면 알레르기가 있어요. (When it comes to cats, I'm allergic.)", "한국 음식이라면 뭐든 좋아요. (When it comes to Korean food, I like anything.)"],
  285: ["비가 오거들랑 전화해요. (If it rains, call me.)", "시간이 나거들랑 놀러 와요. (If you have free time, come visit.)"],
  286: ["연습하노라면 언젠가 잘하게 돼요. (If you keep practicing, someday you'll get good at it.)", "살다 보면 좋은 일도 생기는 법이에요. (If you keep on living, good things will also happen.)"],
  287: ["생각건대 그 방법이 최선이에요. (In my opinion, that method is best.)", "바라건대 모두 건강하길 바랍니다. (I hope everyone will be healthy.)"],
  288: ["열심히 하건만 결과가 안 나와요. (I work hard, but the results don't come.)", "노력은 했건만 실패했어요. (I made effort, but I failed.)"],
  289: ["이미 결정했기로서니 바꿀 수 없어요. (Even so, since it's already decided, we can't change it.)", "늦었기로서니 지금이라도 시작해요. (Even so that it's late, let's start now at least.)"],
  290: ["노력하느니만큼 결과를 기대할 수 있어요. (Inasmuch as you put in effort, you can expect results.)", "공부하느니만큼 실력이 쌓여요. (Inasmuch as you study, skills accumulate.)"],
  291: ["성실하되 유연하게 일하세요. (Work diligently but flexibly.)", "규칙은 지키되 상황을 봐 가며 해요. (Follow the rules, but do so with an eye on the situation.)"],
  292: ["잘 보이디 어디 봐라. (Let me see if you can really do it.)"],
  293: ["진심이라야 마음이 통해요. (Only if it's sincere will hearts connect.)", "노력이라야 성공할 수 있어요. (Only through effort can one succeed.)"],
  294: ["갈 수 있으련마는 시간이 없어요. (I could go, but I have no time.)", "말하고 싶으련마는 참아요. (I want to say it, but I'll hold back.)"],
  295: ["먹자니 배가 부르고 안 먹자니 아깝다. (If I eat, I'm full; if I don't eat, it's a waste.)", "가자니 멀고 안 가자니 보고 싶다. (Going is far, but not going means I'll miss them.)"],
  296: ["빨리 오라고 전화했어요. (I called to tell them to come quickly.)", "조용히 하라고 말했어요. (I told them to be quiet.)"],
  297: ["빨리 가자면 택시를 타야 해요. (If we want to go quickly, we should take a taxi.)", "많이 먹자면 돈이 많아야 해요. (To eat a lot, you need a lot of money.)"],
  298: ["가든들 뭐가 달라지겠어요. (Even if I go, what would change?)", "말한들 소용없어요. (Even if I say it, it's no use.)"],
  299: ["힘들망정 포기는 하지 않겠어요. (Even though it's difficult, I won't give up.)", "가난할망정 행복하게 살아요. (Even though I'm poor, I live happily.)"],
  300: ["생각을 정리할라치면 전화가 와요. (Whenever I try to organize my thoughts, a call comes.)", "자리에 앉을라치면 누가 불러요. (Whenever I try to sit down, someone calls me.)"],
  301: ["날씨가 참 좋은구려! (The weather is really nice!)", "그 사람이 벌써 왔구려! (That person is already here!)"],
  302: ["어, 비가 오는구먼. (Oh, it's raining.)", "그 사람이 또 늦는구먼. (That person is late again.)"],
  303: ["그러시그려, 그렇게 하지요. (I see, let's do it that way.)", "참 좋은 생각이그려. (What a good idea.)"],
  304: ["내년에는 꼭 합격하리라. (I will certainly pass next year.)", "언젠가는 돌아오리라. (I will surely return someday.)"],
  305: ["잠시 기다리시오. (Please wait a moment.)", "이리로 오시오. (Please come this way.)"],
  306: ["왜 이제 왔으니? (Why did you come only now?)", "그때 왜 말 안 했으니? (Why didn't you say something then?)"],
  307: ["바쁘거들랑 나중에 해요. (If you're busy, do it later.)", "필요하거들랑 가져가요. (If you need it, take it.)"],
  308: ["어서 오게. (Come on in.)", "빨리 먹게. (Go ahead and eat.)"],
  309: ["이제 가게. 기다리고 있을게. (Go now. I'll be waiting.)", "잊지 말게. 약속한 거야. (Don't forget. You promised.)"],
  310: ["자리에 앉으구려. (Please take a seat.)", "빨리 오구려. (Please come quickly.)"],
  311: ["날씨가 참 좋네. (The weather is really nice.)", "그 음식이 맛있네. (That food is delicious.)"],
  312: ["오늘 날씨가 춥구만. (The weather is cold today.)", "그 사람이 많이 변했구만. (That person has changed a lot.)"],
  313: ["이게 과연 옳은 건가? (Is this truly the right thing?)", "사랑이란 무엇인가? (What is love?)"],
  314: ["벌써 밥을 먹었나? (Did you already eat?)", "숙제를 다 했나? (Did you finish your homework?)"],
  315: ["그때 거기서 무슨 일이 있었던? (What happened there at that time?)", "예전에 그 사람이 왔던? (Did that person come before?)"],
  316: ["어제 어디 갔던가? (Where did you go yesterday?)", "그 영화 재미있었던가? (Was that movie interesting?)"],
  317: ["작년에 거기 가셨던가요? (Did you go there last year?)", "그분이 누구셨던가요? (Who was that person?)"],
  318: ["해가 밝아 오는 아침이라. (It is a morning with the bright sun rising.)", "꽃이 피는 봄이라. (It is a spring when flowers bloom.)"],
  319: ["그게 사실이리오? (Could that be true?)", "나 없이 어찌 살리오? (How could you live without me?)"],
  320: ["거기 있으시오. (Please stay there.)", "잠시 기다리소. (Please wait a moment.)"],
  321: ["그 사람은 지각하기 일쑤예요. (That person habitually comes late.)", "그 아이는 울기 일쑤예요. (That child cries all the time.)"],
  322: ["그 사람은 귀찮기 짝이 없어요. (That person is incomparably annoying.)", "이 상황은 어이없기 짝이 없어요. (This situation is unbelievably absurd.)"],
  323: ["이미 결혼한 마당에 이제 어쩔 수가 없어요. (Given that they're already married, there's nothing to be done now.)", "이렇게 된 마당에 최선을 다해야 해요. (Given the situation, we have to do our best.)"],
  324: ["죽는 한이 있어도 포기 못 해요. (Even if it means death, I can't give up.)", "힘든 한이 있어도 해 내겠어요. (Even if it means hardship, I will accomplish it.)"],
  325: ["이렇게 살 바에 차라리 포기하는 게 나아요. (If I'm going to live like this, it would be better to give up.)", "거짓말을 할 바에 차라리 말을 안 하는 게 낫죠. (If I'm going to lie, it's better to say nothing.)"],
  326: ["가려도 갈 수가 없어요. (Even if I try to go, I can't.)", "자려도 잠이 안 와요. (Even if I try to sleep, I can't.)"],
  327: ["이번 시험을 잘 볼 것이라는 생각이 들어요. (I have a feeling I'll do well on this exam.)", "그가 올 것이라는 게 믿어져요. (I believe that he will come.)"],
  328: ["남녀를 막론하고 모두 참여했어요. (Everyone participated regardless of gender.)", "나이를 막론하고 누구나 올 수 있어요. (Anyone can come regardless of age.)"],
  329: ["남은 음식을 먹어 치웠어요. (I finished off the remaining food.)", "오래된 문제를 해결해 치웠어요. (I got the old problem over with.)"],
  330: ["그가 온다는 소식을 들었어요. (I heard the news that he is coming.)", "공부를 열심히 한다는 말은 믿기 어려워요. (It's hard to believe the claim that they study hard.)"],
  331: ["친구라고는 한 명도 없어요. (There isn't even a single friend.)", "쓸 만한 것이라고는 없어요. (There's nothing worth using.)"],
  332: ["빨리 오라던가, 어쨌거나 왔어요. (Was it 'come quickly' or something? Anyway, I came.)", "조용히 하라던가 선생님이 말씀하셨어요. (The teacher said something like 'be quiet'.)"],
  333: ["그렇게 하래서야 어떻게 따르겠어요? (How can I follow if you tell me to do it like that?)", "매일 오래서야 힘들지 않겠어요? (Wouldn't it be hard if they tell you to come every day?)"],
  334: ["꼭 성공하리라고 믿어요. (I believe I will certainly succeed.)", "그가 돌아오리라고 생각해요. (I think he will return.)"],
  335: ["먹자면 배가 고프다는 뜻이에요. (If I say let's eat, it means I'm hungry.)", "자자면 피곤하거나 늦은 거죠. (If I say let's sleep, it means I'm tired or it's late.)"],
};

data.forEach((item, idx) => {
  if (examples[idx]) {
    item.examples = examples[idx];
  }
});

fs.writeFileSync(dataPath, JSON.stringify(data, null, 2), 'utf8');

const updated = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
const stillEmpty = updated.filter(item => !item.examples || item.examples.length === 0);
console.log('Still empty:', stillEmpty.length);
if (stillEmpty.length > 0) {
  stillEmpty.forEach(item => console.log(updated.indexOf(item), item.form));
}
console.log('Done. Total items:', updated.length);
