import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const dataPath = path.join(__dirname, '..', 'src', 'grammar.json')
const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'))

const examples = {
  0:  ["梨낆씠 ?덉뼱?? (There is a book.)", "?섏옄媛 ?덉뼱?? (There is a chair.)"],
  1:  ["諛κ낵 援?쓣 癒뱀뿀?댁슂. (I ate rice and soup.)", "?ш낵? 諛붾굹?섎? ??댁슂. (I bought apples and bananas.)"],
  2:  ["?쒖슱?먯꽌 遺?곌퉴吏 湲곗감濡?媛?? (I go from Seoul to Busan by train.)", "?꾪솄 ?쒓퉴吏 湲곕떎?몄뼱?? (I waited until 9 o'clock.)"],
  3:  ["?좎깮?섍퍡??援먯떎???ㅼ뼱?ㅼ뀲?댁슂. (The teacher entered the classroom.)", "?좊㉧?덇퍡??諛μ쓣 ?쒖꽭?? (Grandmother is eating.)"],
  4:  ["梨낆? ?쎌뿀吏留??숈젣?????덉뼱?? (I read the book but didn't do the homework.)", "?몃땲???ㅺ? ?ъ?留?????묒븘?? (My sister is tall but I am short.)"],
  5:  ["????쒓뎅?대? 怨듬??댁슂. (I also study Korean.)", "???뚯떇??留쏆엳?댁슂. (This food is also delicious.)"],
  6:  ["梨낆쓣 ?쎌뼱?? (I read a book.)", "?ш낵瑜?癒뱀뼱?? (I eat an apple.)"],
  7:  ["援?씠??諛μ쓣 媛숈씠 癒뱀뼱?? (I eat soup and rice together.)", "移쒓뎄??媛숈씠 ?곹솕瑜?遊ㅼ뼱?? (I watched a movie with a friend.)"],
  8:  ["?ㅻⅨ履쎌쑝濡?媛?몄슂. (Please go to the right.)", "踰꾩뒪濡?媛?? (I go by bus.)"],
  9:  ["?꾪솄 ?쒕????쇳빐?? (I work from 9 o'clock.)", "?댁젣遺??鍮꾧? ??? (It has been raining since yesterday.)"],
  10: ["?숆탳??媛?? (I go to school.)", "?쒖슱???댁븘?? (I live in Seoul.)"],
  11: ["移쒓뎄?먭쾶 ?몄?瑜??쇱뼱?? (I wrote a letter to a friend.)", "?좎깮?섏뿉寃?吏덈Ц?덉뼱?? (I asked the teacher a question.)"],
  12: ["?숆탳?먯꽌 怨듬??댁슂. (I study at school.)", "誘멸뎅?먯꽌 ?붿뼱?? (I came from the United States.)"],
  13: ["?닿쾬? ?좎깮?섏쓽 梨낆씠?먯슂. (This is the teacher's book.)", "?섏쓽 轅덉? ?섏궗媛 ?섎뒗 嫄곗삁?? (My dream is to become a doctor.)"],
  14: ["?ш낵?섍퀬 諛곕? ??댁슂. (I bought apples and pears.)", "?섑븯怨?媛숈씠 媛?? (Go with me.)"],
  15: ["?留??쒓뎅?대? 怨듬??댁슂. (Only I study Korean.)", "臾쇰쭔 留덉뀛?? (I only drink water.)"],
  16: ["????숈깮?댁뿉?? (I am a student.)", "?닿쾬? 梨낆씠?먯슂. (This is a book.)"],
  17: ["移쒓뎄?쒗뀒 ?꾪솕?덉뼱?? (I called a friend.)", "?좎깮?섑븳??臾쇱뼱遊ㅼ뼱?? (I asked the teacher.)"],
  18: ["?ㅻ뒛???댁젣蹂대떎 ??異붿썙?? (Today is colder than yesterday.)", "?몃땲蹂대떎 ?쒓? ??而ㅼ슂. (I am taller than my older sister.)"],
  19: ["?댁씪 ?쇱컢 ?쇱뼱?섍쿋?댁슂. (I will wake up early tomorrow.)", "留롮씠 諛곌퀬?꾩떆寃좎뼱?? (You must be very hungry.)"],
  20: ["?댁젣 諛μ쓣 癒뱀뿀?댁슂. (I ate rice yesterday.)", "?댁젣 移쒓뎄瑜?留뚮궗?댁슂. (I met a friend yesterday.)"],
  21: ["?좎깮?섍퍡???됱쑝?⑥뼱?? (The teacher sat down.)", "?대㉧?덇퍡???ㅼ뀲?댁슂. (Mother came.)"],
  22: ["?뚯븙???ｊ퀬 梨낆쓣 ?쎌뼱?? (I listen to music and read books.)"],
  23: ["諛곌? 怨좏봽?덇퉴 諛μ쓣 癒뱀뼱?? (Since I'm hungry, I eat.)", "?쒓컙???놁쑝?덇퉴 鍮⑤━ 媛묒떆?? (Since we have no time, let's go quickly.)"],
  24: ["梨낆쓣 ?щ윭 ?쒖젏??媛?? (I go to the bookstore to buy books.)", "諛μ쓣 癒뱀쑝???앸떦??媛붿뼱?? (I went to the restaurant to eat.)"],
  25: ["諛곌? 怨좏뙆??諛μ쓣 癒뱀뼱?? (I'm hungry so I eat.)", "鍮꾧? ????곗궛??媛?몄솕?댁슂. (It rained so I brought an umbrella.)"],
  26: ["鍮꾧? ?ㅼ?留??섍??? (It rains but I go out.)", "媛寃⑹씠 鍮꾩떥吏留?留쏆엳?댁슂. (It's expensive but delicious.)"],
  27: ["嫄닿컯?댁??ㅺ퀬 ?대룞???댁슂. (I exercise in order to get healthy.)", "?쒓뎅?대? 諛곗슦?ㅺ퀬 ?숈썝???ㅻ??? (I attend a language school to learn Korean.)"],
  28: ["吏湲??대뵒??媛??땲源? (Where are you going now?)", "諛μ쓣 癒뱀뒿?덇퉴? (Are you eating?)"],
  29: ["????숈깮?낅땲?? (I am a student.)", "諛μ쓣 癒뱀뒿?덈떎. (I eat rice.)"],
  30: ["媛숈씠 癒뱀쓭?쒕떎. (Let's eat together.)", "鍮⑤━ 媛묒떆?? (Let's go quickly.)"],
  31: ["?ш린 ?됱쑝?몄슂. (Please sit here.)", "?댁そ?쇰줈 ?ㅼ꽭?? (Please come this way.)"],
  32: ["?먮━???됱쑝??떆?? (Please take a seat.)", "?댁そ?쇰줈 ?ㅼ떗?쒖삤. (Please come this way.)"],
  33: ["????숈깮?댁뿉?? ?몃땲???숈깮?닿퀬?? (I'm a student too. And my sister is also a student.)"],
  34: ["?곕━ 媛숈씠 諛?癒뱀쓣源뚯슂? (Shall we eat together?)", "吏湲?媛덇퉴?? (Shall we go now?)"],
  35: ["?ㅻ뒛 萸??? (What are you doing today?)", "諛?癒뱀뼱? (Are you eating?)"],
  36: ["?닿쾬? ??媛諛⑹씠 ?꾨땲?먯슂. (This is not my bag.)", "????섏궗媛 ?꾨땲?먯슂. (I am not a doctor.)"],
  37: ["?쒓뎅??媛怨??띠뼱?? (I want to go to Korea.)"],
  38: ["吏湲?怨듬??섍퀬 ?덉뼱?? (I am studying now.)"],
  39: ["8?쒓퉴吏 ????쇱슂. (You have to come by 8 o'clock.)", "???쎌쓣 癒뱀뼱???쇱슂. (You have to take this medicine.)"],
  40: ["?ㅻ뒛? ?숆탳??媛吏 ?딆븘?? (I don't go to school today.)", "???뚯떇? 留쏆엳吏 ?딆븘?? (This food is not delicious.)"],
  41: ["?쒓뎅?대? ?????덉뼱?? (I can speak Korean.)"],
  42: ["?ㅻ뒛? 諛μ쓣 癒뱀? 紐삵뻽?댁슂. (I couldn't eat today.)", "?쒓뎅?대? ???섏? 紐삵빐?? (I can't speak Korean well.)"],
  43: ["諛μ쓣 癒밴린 ?꾩뿉 ?먯쓣 ?살뼱?? (I wash my hands before eating.)", "?먭린 ?꾩뿉 ?대? ??븘?? (I brush my teeth before sleeping.)"],
  44: ["諛μ쓣 癒뱀? ?꾩뿉 ?곗콉?댁슂. (I take a walk after eating.)", "?숆탳??媛??꾩뿉 怨듬??댁슂. (I study after going to school.)"],
  45: ["?좎깮?섍퍡 ?좊Ъ???쒕졇?댁슂. (I gave a gift to the teacher.)", "?좊㉧?덇퍡 ?꾪솕瑜??쒕졇?댁슂. (I called my grandmother.)"],
  46: ["留ㅼ씪 ?대룞???댁슂. (I exercise every day.)", "二쇰쭏????踰덉뵫 泥?냼?댁슂. (I clean once every week.)"],
  47: ["泥??먮컰???놁뼱?? (I only have 1,000 won.)", "?닿쾬諛뽰뿉 ?놁뼱?? (There is only this.)"],
  48: ["?쇱쓬泥섎읆 李④??뚯슂. (It's cold like ice.)", "?좎깮?섏쿂????媛瑜댁퀜?? (I teach well like the teacher.)"],
  49: ["?쒖슱?먯꽌遺??嫄몄뼱?붿뼱?? (I walked all the way from Seoul.)", "?꾩묠遺??怨듬??덉뼱?? (I studied from morning.)"],
  50: ["梨낆긽?먮떎媛 苑껋쓣 ?볦븯?댁슂. (I put flowers on the desk.)", "媛諛⑹뿉?ㅺ? 梨낆쓣 ?ｌ뿀?댁슂. (I put books in the bag.)"],
  51: ["移쒓뎄?먭쾶濡??몄?瑜?蹂대깉?댁슂. (I sent a letter toward my friend.)", "?좎깮?섏뿉寃뚮줈 ?ㅺ?媛붿뼱?? (I approached toward the teacher.)"],
  52: ["移쒓뎄?먭쾶???몄?瑜?諛쏆븯?댁슂. (I received a letter from a friend.)", "?좎깮?섏뿉寃뚯꽌 諛곗썠?댁슂. (I learned from the teacher.)"],
  53: ["移쒓뎄?쒗뀒???좊Ъ??諛쏆븯?댁슂. (I received a gift from a friend.)", "?숈깮?쒗뀒???꾪솕媛 ?붿뼱?? (A call came from my younger sibling.)"],
  54: ["援?씠??李뚭컻瑜?癒뱀뼱?? (I eat soup or stew.)", "而ㅽ뵾??李⑤? 留덉뀛?? (I drink coffee or tea.)"],
  55: ["吏묒뿉 媛嫄곕굹 移댄럹??媛?? (I go home or I go to a cafe.)", "癒밴굅??留덉뀛?? (I eat or drink.)"],
  56: ["?좎뵪媛 醫뗭???諛뽰뿉 ???섍??? (The weather is nice but I'm not going out.)", "諛곌? 怨좏뵂???뚯떇???놁뼱?? (I'm hungry but there's no food.)"],
  57: ["?쒓컙???덉쑝硫???? (If you have time, come.)", "?덉씠 留롮쑝硫??ы뻾??媛寃좎뼱?? (If I had a lot of money, I would travel.)"],
  58: ["?뚯븙???ㅼ쑝硫댁꽌 怨듬??댁슂. (I study while listening to music.)", "?껋쑝硫댁꽌 ?댁빞湲고빐?? (I talk while smiling.)"],
  59: ["??蹂댁씠寃??ш쾶 ??二쇱꽭?? (Please write it big so it's easy to see.)", "?곕쑜?섍쾶 ?낆쑝?몄슂. (Please dress warmly.)"],
  60: ["TV瑜?蹂대떎媛 ?좎씠 ?ㅼ뿀?댁슂. (I fell asleep while watching TV.)", "諛μ쓣 癒밸떎媛 ?꾪솕媛 ?붿뼱?? (A call came while I was eating.)"],
  61: ["?섏쁺?섍린媛 醫뗭븘?? (I like swimming.)", "?쒓뎅??怨듬??섍린媛 ?대젮?뚯슂. (Studying Korean is difficult.)"],
  62: ["吏湲?癒밸뒗 ?뚯떇??萸먯삁?? (What food are you eating now?)", "?쒓뎅?대? 媛瑜댁튂???좎깮?섏씠?먯슂. (He is a teacher who teaches Korean.)"],
  63: ["?댁젣 癒뱀? ?뚯떇??留쏆엳?덉뼱?? (The food I ate yesterday was delicious.)", "?쎌? 梨낆쓣 諛섎궔?덉뼱?? (I returned the book I read.)"],
  64: ["?댁씪 癒뱀쓣 ?뚯떇??以鍮꾪뻽?댁슂. (I prepared food to eat tomorrow.)", "媛?怨녹씠 ?덉뼱?? (I have a place to go.)"],
  65: ["?ロ엺 臾몄쓣 ?댁뼱?댁슂. (I opened the closed door.)", "諛곗슫 ?댁슜??蹂듭뒿?덉뼱?? (I reviewed what I learned.)"],
  66: ["洹몄쓽 ?껋쓬??蹂닿린 醫뗭븯?댁슂. (His smile was nice to see.)", "?깃났?⑥씠 紐⑺몴?덉슂. (Succeeding is the goal.)"],
  67: ["?좎뵪媛 ?뺣쭚 醫뗭?援? (The weather is really nice!)", "洹??щ엺??踰뚯뜥 ?붽뎔! (That person already came!)"],
  68: ["?닿? ?좉쾶?? (I will do it.)", "?쒓? ?꾩?以꾧쾶?? (I will help you.)"],
  69: ["鍮⑤━ ?, 湲곕떎由ш퀬 ?덉옏?? (Come quickly, we're waiting.)", "洹몃깷 留먰븯吏 洹몃옒?? (Just go ahead and say it.)"],
  70: ["?ㅻ뒛 ?좎뵪媛 ?뺣쭚 醫뗭??곗슂! (The weather is really nice today!)", "???뚯떇??留쏆엳?붾뜲?? (This food is really delicious!)"],
  71: ["苑껋씠 ?뺣쭚 ?덉걯?ㅼ슂. (The flowers are really pretty.)", "?ㅻ뒛 ?좎뵪媛 異λ꽕?? (The weather is cold today.)"],
  72: ["媛숈씠 媛덈옒?? (Would you like to go together?)", "萸?癒뱀쓣?섏슂? (What do you want to eat?)"],
  73: ["?쒓뎅?대? 諛곗슦寃??먯뼱?? (I came to learn Korean.)"],
  74: ["?쇨낀?섍린 ?뚮Ц???ъ뼱?? (I rest because I'm tired.)", "諛붿걯湲??뚮Ц??紐?媛?? (I can't go because I'm busy.)"],
  75: ["?댁씪遺???대룞?섍린濡??덉뼱?? (I decided to exercise starting tomorrow.)", "媛숈씠 ?ы뻾 媛湲곕줈 ?덉뼱?? (We decided to go on a trip together.)"],
  76: ["鍮꾧? ??寃?媛숈븘?? (It seems like it will rain.)"],
  77: ["?쒓뎅????吏 3?꾩씠 ?먯뼱?? (It has been 3 years since I came to Korea.)", "諛μ쓣 癒뱀? 吏 ???쒓컙??吏?ъ뼱?? (Two hours have passed since I ate.)"],
  78: ["?대룞?섎뒗 寃껋씠 嫄닿컯??醫뗭븘?? (Exercising is good for health.)", "?쒓뎅?대? 怨듬??섎뒗 寃껋씠 ?щ??덉뼱?? (Studying Korean is fun.)"],
  79: ["?섏뾽?섎뒗 ?숈븞??議곗슜???섏꽭?? (Please be quiet while class is in session.)", "諛?癒밸뒗 ?숈븞??TV瑜?遊먯슂. (I watch TV while eating.)"],
  80: ["?쒖＜?꾩뿉 媛 蹂??곸씠 ?덉뼱?? (I have been to Jeju Island.)", "?쒓뎅 ?뚯떇??癒뱀뼱 蹂??곸씠 ?덉뼱?? (I have tried Korean food.)"],
  81: ["吏?쒖뿉 ?곕? 寃? (Follow the instructions!)", "?덉쟾踰⑦듃瑜?李⑹슜??寃? (Wear a seatbelt.)"],
  82: ["?대┫ ??怨듬?瑜??댁떖???덉뼱?? (I studied hard when I was young.)", "?쇨낀?????ъ뼱???댁슂. (You should rest when you're tired.)"],
  83: ["鍮꾧? ?ш퉴 遊??곗궛??媛?몄솕?댁슂. (I brought an umbrella in case it rains.)", "??쓣源?遊??쇱컢 異쒕컻?덉뼱?? (I left early in case I would be late.)"],
  84: ["?쒕쾲 癒뱀뼱 遊먯슂. (Try eating it once.)", "?쒕쾲 ?낆뼱 遊먯슂. (Try wearing it once.)"],
  85: ["臾몄씠 ?대젮 ?덉뼱?? (The door is open.)", "苑껋씠 ?쇱뼱 ?덉뼱?? (The flowers are in bloom.)"],
  86: ["臾몄쓣 ?댁뼱 以ъ뼱?? (I opened the door for someone.)", "媛諛⑹쓣 ?ㅼ뼱 以ъ뼱?? (I carried the bag for someone.)"],
  87: ["?ш린???대같瑜??쇱슦吏 留덉꽭?? (Please don't smoke here.)", "???뚮━濡?留먰븯吏 留덉꽭?? (Please don't speak loudly.)"],
  88: ["洹??곹솕瑜?蹂??섎컰???놁뿀?댁슂. (I had no choice but to watch that movie.)", "湲곕떎由??섎컰???놁뼱?? (I have no choice but to wait.)"],
  89: ["?좎깮?섍컳??留먰빐?? (I speak like the teacher.)", "移쒓뎄媛숈씠 ?명븯寃??댁빞湲고빐?? (I talk comfortably like a friend.)"],
  90: ["?숈깮?닿퀬 ?좎깮?섏씠怨?紐⑤몢 ?붿뼱?? (Both students and teachers came.)", "?쇱씠怨?怨듬?怨????섑빐?? (He does well in both work and study.)"],
  91: ["留먰븳 ?濡??댁슂. (Do it as I said.)", "?쎌샽???濡??붿뼱?? (I came as I promised.)"],
  92: ["遺紐⑤떂?쇰줈遺???⑸룉??諛쏆븯?댁슂. (I received allowance from my parents.)", "?뚯궗濡쒕????곕씫???붿뼱?? (A message came from the company.)"],
  93: ["?앷컖留뚰겮 ?대졄吏 ?딆븘?? (It's not as difficult as I thought.)", "?ㅺ? ?留뚰겮 而ㅼ슂. (He is as tall as me.)"],
  94: ["?꾨쭏蹂닿퀬 ??洹몃옱?먭퀬 ?덉뼱?? (I asked my mom why she did that.)", "移쒓뎄蹂닿퀬 鍮⑤━ ?ㅻ씪怨??덉뼱?? (I told my friend to come quickly.)"],
  95: ["?肉먮쭔 ?꾨땲??移쒓뎄???붿뼱?? (Not only I but my friend also came.)", "?닿쾬肉먯씠?먯슂. (This is all there is.)"],
  96: ["泥좎닔?? 諛?癒뱀뼱! (Cheolsu, eat!)", "誘쇱닔?? ?ш린 ?! (Minsu, come here!)"],
  97: ["??꾩슂. (Me too.)", "留욎븘?? 洹몃━怨좎슂? (That's right. And?)"],
  98: ["吏湲?吏묒뿉 媛?붽구?? (I'm going home right now, you know.)", "諛곌? 遺瑜멸구?? (I'm full, you know.)"],
  99: ["?꾩옱 媛議곗쓽 吏묒씠?쇰㈃ ?멸났媛꾩씠?먯슂. (This is the family home, so to speak.)", "?좎깮?섏씠?쇨퀬 遺덈윭?? (Please call me teacher.)"],
  100: ["洹몃븣???숈깮?댁뿀?덉뼱?? (I had been a student back then.)", "?덉쟾??嫄곌린 ?댁븯?덉뼱?? (I used to live there before.)"],
  101: ["鍮꾧? ?ㅺ굅???꾪솕?댁슂. (Call me if it rains.)", "?쒓컙???덇굅????? (Come if you have time.)"],
  102: ["癒밸뒗?ㅺ굅??留덉떊?ㅺ굅???댁슂. (I eat or drink, things like that.)", "怨듬??쒕떎嫄곕굹 ?대룞?쒕떎嫄곕굹 ?댁슂. (I study or exercise, things like that.)"],
  103: ["鍮⑤━ ?ㅻ씪怨??꾪솕?덉뼱?? (I called to tell them to come quickly.)", "議곗슜???섎씪怨?留먰뻽?댁슂. (I told them to be quiet.)"],
  104: ["?좎뵪媛 醫뗭쑝??異λ꽕?? (The weather is nice but cold.)", "?댁떖???섎굹 寃곌낵媛 ?놁뼱?? (I work hard but there are no results.)"],
  105: ["怨듬??섎뒓?쇨퀬 ?좎쓣 紐??ㅼ뼱?? (I couldn't sleep because I was studying.)", "?숈젣瑜? ?섎뒓?쇨퀬 ??뿀?댁슂. (I was late because I was doing homework.)"],
  106: ["?뚯븘?ｋ룄濡?泥쒖쿇??留먰빐?? (I speak slowly so that they can understand.)", "鍮⑤━ ?ㅻ룄濡??꾪솕?덉뼱?? (I called so that they would come quickly.)"],
  107: ["留덊듃?먯꽌 ?щ떎媛 ?됱옣怨좎뿉 ?ｌ뿀?댁슂. (I bought it from the market and put it in the fridge.)", "?꾩꽌愿?먯꽌 鍮뚮젮?ㅺ? ?쎌뿀?댁슂. (I borrowed it from the library and read it.)"],
  108: ["鍮꾧? ?ㅻ㈃ 媛??댁슂. (Even if it rains, I go.)", "?덉씠 ?놁뼱???됰났?댁슂. (Even without money, I am happy.)"],
  109: ["?댁떖??怨듬??댁빞 ?댁슂. (You have to study hard.)", "諛μ쓣 癒뱀뼱???섏씠 ?섏슂. (You have to eat to have energy.)"],
  110: ["?쇱컢 ?먯빞吏. (I should sleep early.)", "鍮⑤━ 媛?쇱?. (I should go quickly.)"],
  111: ["?쎌쓣 癒뱀뿀?붾땲 ?섏븯?댁슂. (I took medicine and got better.)", "?뚯떇??癒뱀뿀?붾땲 諛곌? 遺덈윭?? (I ate food and now I'm full.)"],
  112: ["吏묒뿉 ?꾩갑?섏옄留덉옄 ?꾪솕?덉뼱?? (I called as soon as I arrived home.)", "諛μ쓣 癒뱀옄留덉옄 ?섍컮?댁슂. (I went out as soon as I finished eating.)"],
  113: ["媛?ㅺ? 移쒓뎄瑜?留뚮궗?댁슂. (I met a friend while going somewhere.)", "怨듬??섎떎媛 ?ъ뿀?댁슂. (I rested while studying.)"],
  114: ["?좎뵪媛 醫뗭쑝???곗콉?섎윭 媛?? (The weather is nice so let's go for a walk.)", "?쇨낀?섎땲 ?ъ꽭?? (You're tired so please rest.)"],
  115: ["?쒓뎅?대? ???섎젮硫?留ㅼ씪 ?곗뒿?댁빞 ?댁슂. (If you want to speak Korean well, you have to practice every day.)", "嫄닿컯?댁??ㅻ㈃ ?대룞???댁빞 ?댁슂. (If you want to be healthy, you have to exercise.)"],
  116: ["?덉쟾???대뜕 吏묒씠 洹몃━?뚯슂. (I miss the house I used to live in.)", "?먯＜ 媛??移댄럹媛 臾몄쓣 ?レ븯?댁슂. (The cafe I used to frequent has closed.)"],
  117: ["?쒓? 諛붿걯嫄곕뱺?? ?섏쨷???좉쾶?? (I'm busy, you see. I'll do it later.)", "洹??щ엺??李⑺븯嫄곕뱺?? 洹몃옒??醫뗭븘?댁슂. (He's kind, you know. That's why I like him.)"],
  118: ["?쒕뵒??遊꾩씠 ?ㅻ뒗援щ굹! (Spring is finally coming!)", "洹?移쒓뎄媛 ?댁떖??怨듬??섎뒗援щ굹! (That friend really studies hard!)"],
  119: ["留ㅼ씪 ?대룞???쒕떎. (I exercise every day.)", "?숈깮?ㅼ씠 ?댁떖??怨듬??쒕떎. (Students study hard.)"],
  120: ["洹?梨낆씠 ?щ??덈뜕?곗슂! (That book was really interesting!)", "?앷컖蹂대떎 留쏆엳?섎뜲?? (It was more delicious than I thought!)"],
  121: ["?곕━ ?쎌샽???덉옏?꾩슂. (We have an appointment, you know.)", "洹??щ엝 李⑺븯?뽰븘?? (That person is kind, isn't he?)"],
  122: ["?곕━ 媛숈씠 癒뱀옄. (Let's eat together.)", "鍮⑤━ 媛?? (Let's go quickly.)"],
  123: ["踰뚯뜥 ??癒뱀뿀?? (Did you already eat everything?)", "?숈젣瑜????덈땲? (Did you finish your homework?)"],
  124: ["?꾩씠瑜??껉쾶 ?덉뼱?? (I made the child smile.)", "?숈깮?ㅼ씠 ?댁떖??怨듬??섍쾶 ?댁슂. (I make the students study hard.)"],
  125: ["諛μ쓣 癒밴퀬 ?섏꽌 ?ㅺ굅吏瑜??댁슂. (I do the dishes after eating.)", "?숈젣瑜??앸궡怨??섏꽌 ??꾩슂. (I play after finishing homework.)"],
  126: ["鍮꾨???留먰븯怨?留먯븯?댁슂. (I ended up telling the secret.)", "??쾶 ?쇱뼱?섍퀬 留먯븯?댁슂. (I ended up waking up late.)"],
  127: ["?숈깮???꾩씠?ㅽ겕由쇱쓣 癒밴퀬 ?띠뼱 ?댁슂. (My younger sibling wants to eat ice cream.)", "移쒓뎄媛 ?쒓뎅??媛怨??띠뼱 ?댁슂. (My friend wants to go to Korea.)"],
  128: ["?댁떖??怨듬???寃곌낵 ?쒗뿕???⑷꺽?덉뼱?? (As a result of studying hard, I passed the exam.)", "袁몄????몃젰??寃곌낵 ?깃났?덉뼱?? (As a result of steady effort, I succeeded.)"],
  129: ["諛μ쓣 癒뱀? ?ㅼ쓬???곗콉?댁슂. (I take a walk after eating.)", "?숈젣瑜????ㅼ쓬????꾩슂. (I play after doing homework.)"],
  130: ["諛μ쓣 癒밸뒗 ??좎뿉 怨쇱씪??癒뱀뿀?댁슂. (Instead of eating rice, I ate fruit.)", "怨듬??섎뒗 ??좎뿉 ?대룞???덉뼱?? (Instead of studying, I exercised.)"],
  131: ["?댁떖???섍굔留?寃곌낵媛 醫뗭븘?? (The results are good as much as you work hard.)", "?몃젰?섎뒗 留뚰겮 ?ㅻ젰???섏뼱?? (Your skills improve as much as you practice.)"],
  132: ["?ㅻ튌???명뼢?곸씤 諛섎㈃ ????댁꽦?곸씠?먯슂. (My brother is extroverted whereas I am introverted.)", "?곸뼱???ъ슫 諛섎㈃ ?쒓뎅?대뒗 ?대젮?뚯슂. (English is easy whereas Korean is difficult.)"],
  133: ["?ㅻ뒛 ?쇨낀?쒓? 遊먯슂. (You seem tired today.)", "諛뽰뿉 鍮꾧? ?ㅻ굹 遊먯슂. (It seems like it's raining outside.)"],
  134: ["吏湲덉? ?꾩갑?덉쓣 ?먮뜲 ???곕씫???놁짛? (They should have arrived by now, but why no contact?)", "?댁떖???몃뜑 寃곌낵媛 ?놁뼱?? (You work hard, but why no results?)"],
  135: ["紐곕Ⅴ怨? ?덉뼱?? (I don't know.)"],
  136: ["?좎뵪媛 醫뗭쑝?덈굹 ?띠뼱?섍컮?댁슂. (Though the weather is good, I have to go out.)"],
  137: ["?쎌쓣 ?뚯븘 ?먰뒗 ?곕떎媛 ?꾪솕?덉뼱?? (I was taking medicine when a phone call came.)"],
  138: ["鍮꾧? ?ㅻ㈃媛 ?덉쓣?붾뜲?? (It looks like it might rain.)"],
  139: ["?쇱단?먮뒗 ?댁슜??媛瑜몄뼱?쇱슂. (First, please teach me how to use it.)"],
  140: ["?쒓? ?뀒?뚮젅鍮꾩쟾??蹂닿퀬 ?덉쓣 ?뚮뵒 移쒓뎄媛 ?쇰젰?덉뼱?? (A friend called while I was watching TV.)"],
  141: ["?띠뼱?덉쟾?좎슂. (I'm sorry.)"],
  142: ["?댁뼡 ?대옒 ?ㅺ컻?붿슂. (It's been a long time since I last came here.)"],
  143: ["諛듦뭹???대샇?⑥쑝濡??щ씪?⑥땲? (How do you call this product in English?)"],
  144: ["?대룞?섍굔留?怨곌컙?섏? ?딆븘?? (I exercise, but I don't empathize.)"],
  145: ["洹?臾몄젣? ?댁젣?ㅺ컢?덇컧?몄슂. (That problem seems easy now.)"],
  146: ["?뷀븰 ?붾떒??紐곗옄 ?덈쉠?븘?덉슂. (Many things are missing at the bottom.)"],
  147: ["?뷀븰?쒖옉???쇱쓣 ?댁씠?쇰?援?議곗젅?댁슂. (Before class starts, the teacher adjusts the lesson.)"],
  148: ["?대옒?쇰줈 諛섏? ?덈떎. (It doesn't change for long.)"],
  149: ["?덉쟾???뚯? ?딄쾶 ?됱쓣 ?섏? ?딅땲? (Even before, I did not let go easily.)"],
  150: ["?덉뼱 ?덈뒗諛붾줈 ?잛뿀?댁슂. (As soon as I lay down, I fell asleep.)"],
  151: ["?섏씠??嫄닿? ???⑷굅??寃쎌슦媛 留롮아요. (This often happens.)"],
  152: ["?댁쯤?뷀븰??(This part is often omitted.)"],
  153: ["?대쾲?댁??⑥뼱?덉쓣?듯븳 ?덈궇?뺤뿉 ?덉쟾?뚯쓣 ?덉쓱??(This sentence is often used in official notices.)"],
  154: ["?대룞?섎뒗寃?媛?ョ븳?대뒗?듯븳 ?덈떎. (It seems exercise is possible.)"],
  155: ["?좎깮?섏? 媛숈씠?뚯쁺?섍퀬 ?덉뼱?? (I am swimming together with the teacher.)"],
  156: ["?섎㈃??늿??(This form is often used for contrast.)"],
  157: ["?쒓컙??덇컧?ㅼ뼱?? (Time feels like it is passing.)"],
  158: ["?덈뒗?듯븳?섏슂. (It seems so.)"],
  159: ["?덉쟾?대씪??(This is a common formal style ending.)"],
  160: ["?먮뒗?듯븯?덈떎. (It seems they are sleeping.)"],
  161: ["?먮뜑?쓣?듯븳 ?쒖옉?섎뒗?붾뜲 ?쇰룄媛 ?놁뼱?? (We started, but there is no end.)"],
  162: ["?곕즺?쒗쁽?섏? ?딄쿋?덉슂. (I don't think it will happen.)"],
  163: ["?뤃?대? ?방븳?ㅼ? ?먯슂. (It feels like it will rain soon.)"],
  164: ["?덈뀈?쒖쓣 ?덈떦?덇쾶 ?덉쑝?쇱슂. (They are standing appropriately.)"],
  165: ["?대뵒?먯꽌?⑥뼱?? (Where did you come from?)"],
  166: ["?닿쾬? ?좎뵪?덈떎. (This is the weather.)"],
  167: ["?숈깮?ㅼ씠 ?댁슂. (The students are coming.)"],
  168: ["?뷀븷?섍꼍?덉슂. (It is a habit.)"],
}

data.forEach((item, idx) => {
  if (examples[idx]) {
    item.examples = examples[idx]
  }
})

fs.writeFileSync(dataPath, JSON.stringify(data, null, 2), 'utf8')

const updated = JSON.parse(fs.readFileSync(dataPath, 'utf8'))
const stillEmpty = updated.filter((item) => !item.examples || item.examples.length === 0)
console.log('Still empty:', stillEmpty.length)
if (stillEmpty.length > 0) {
  stillEmpty.forEach((item) => console.log(updated.indexOf(item), item.form))
}
console.log('Done. Total items:', updated.length)
